name: Up to Date
on: push
# on:
#   schedule:
#     - cron: "*/5 * * * *"
jobs:
  update:
    name: Update emoji data files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Update Emoji data files
        run: npm run update-emojis

      - name: Create Pull Request if data files were changed
        uses: peter-evans/create-pull-request@v4
